import Image from "next/image";
import { Geist, Geist_Mono, Siemreap } from "next/font/google";
import { getAllPosts } from "../lib/NotionAPI";
import Head from "next/head";
import SinglePost from "@/components/Posts/SinglePost";

export const getStaticProps = async () => {
  const allPosts = await getAllPosts();
  console.log("allPosts", allPosts);
  return{
    props: {
      allPosts,
    },
    revalidate: 60,
  };
};

export default function Home( {allPosts} ) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog
        </h1>
        {allPosts.map((post) => 
        (
          <div className="mx-4">
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
            />
          </div>
        ))}
      </main>

    </div>
  );
}
